// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qctgjuiaybvjlifomcgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjdGdqdWlheWJ2amxpZm9tY2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTI0MDUsImV4cCI6MjA3MzE4ODQwNX0.V4eCzGqlsrsVy0PKuwieY3HmYwTSPHYGsLt0jjb0HS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});